language: node_js
node_js:
- '10'
install:
- yarn global add codecov
script:
- yarn
- yarn run lint
- yarn run cspell
- yarn codecov
- NODE_ENV=production ONCE=true yarn bundle
- NODE_ENV=dev ONCE=true yarn bundle
- NODE_ENV=production yarn bundle:globals
- NODE_ENV=dev yarn bundle:globals
- yarn build
- yarn types
deploy:
  skip_cleanup: true
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  tag: beta
  api_key:
    secure: "CyPbn3cPmDNR+3qpH2MZ2EBFK/xdUA1cS7HVHRFZHmN2509oAFP8iF1dORny1kGWB9oVRvpGoGU5cc0rJeIpG6rGeb2kOUJpTpqUVF1NEwc8zCl6JeWmkzqoaRGkS/qUnHGfuHki9xYEE+shwO3qmJaAwwJjeq6qP6wmE8lkclMrbkpZ7mRz3gZvCTChB0dMalwPgOc0EBp5AclBSszJ4DOa/emAl6xlFaBOlu1M4+hDGAyj3TvvN3qIFpM69pcJYMUgP23+Y81xOyfMFTykFU6hq7Ah8KtIQMMRvnCcn/K/S9+52aPzYdXMlE8IpzF1PyfsSIdOA2mZbT+Vs9WehmQO9udqQPI6/HIyNTyOOLgngLH3Wa3XsMRZ/09nl+YQwVnuSdduaUU3vjSAkCJSGVk2wfUG5KcJxrs6JkDCICfLSe/W6+NAOEE5Nso7H6TyIggZjL8bghvJKraQ5db4Yycx1FXOgKqCh5PFZWeDKQoXwL24Xlwh4isrUgsCQYSPcE0E6WfHg/NL4cSg2iRl2dfgI3108UQsE0O6qWvmuldo/ZAGk1je89dX57hmmpdkfO9n3Lm5aqus9PGr6nlHWFW11QTTBVb0C8MB8S2gYyc3OYA3kUebK9m/2QMxVbVZlx/X0C4149tIgCz43IqBCcPO904OX+Wenuc01mMl0qQ="
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro
notifications:
  slack:
    secure: ZrGsqnznXqlEHpB+1kSsxqKdtgNXZ5DMLTD3ThIH3H7XPyBCSshBtENJjZxlPpZBWsPBWTrZBGRHGgrsnaB06tFc44KeF4HqxPH0aH6P3oakYVOQD2HiaqSoDghClUngePREAKFKNAVi3AO50nu+TVYKUQoae1tdKY6ZV2OCJ86IbgXB775fn+kW+t0ODGUMtukpFfwTTZTDG5y1AxMojLrnEaoMgmIwwanPKpBiL0gXdRvEG5by31PHz4bA/0vUtR6W45OF7CUn6mO2Q96ZjQ1TKo6dYRymL8ySiOiVZaGbcVZzpjsaTHdq8ZdIqwzPnLPRax1MPQbxul6p1Xu8asHR51/eTZkaBNlAIB++n7YjLxiQuhjNnOFBjc/a1n3FK8h6KxOQikd0He8N+Q+Ksa1wBPNRVsN25VdpGkkAknMIC8YYTOgSkU6KUgeGwC1aVW9/Y/K+Bju2wZNAsF/JR0B7GiAEUWo3Bgx3OvAAuDC2LyWqsTVYMY8rFNZRhdXS/3NSlgxNhm6qphEk4FLFFb6aWbvkAKULwNFax7pe89BMuMEPcEac0ZS+InY3XOfC9ZT1VzqhW4SRih3qvqx9Dbe8tpJdFvmeOYXO78O6dQKGz/+/CVZUk5qKwv0965HmQMuBHYMFveSpbzcxE6ZqXKGUX239ua+GfQE+6FT7K/E=
env:
  global:
    secure: hdr+J22+7YjxcElpW56yj0qFi/nk1Y9SXycoqk7nQMSzEx7rT0exHWu8tqDA1e38AtdMVKwjkYxbm4w3c1W2QefdAyodWCCleTyZ2t7wl/b6qibVfxN4TEdQMPCDmv/buS1Y8eexKrn57eGNGu+OnZOGav0GjAl3jsIv7DoSjuaak5RR59+hq03ufh1KmCrlwUP0C0SAVGQ/SkhL/H1tbs5F9GdTM1U3Y+GepDPkyoIFNBmWSxqJVmJMDPqes9LfiffcTUaq1ko1y47xLPfQ7ZaXY/DzGcX/g+9XKsEfM9AsGmIKyzliw6ZIJ6lnjjajiTeq+3PPjicMSSevppUagFs9IveDAuPmn0g40Djyb9FrFZWhSs35PSFWWYhUgXHxRKh6T91wQZM3Np/Hx1WjXZoD3KxGnig4kfriUVrm3rvvikC4Fhn110xfoeu8fgE91PgGBMuMa9+V37qQfKElOFk1EUTuXCTJ6tMvOtBSNCqrOdiQaxKOAuDHOG+ej2k43SpOsmLi2asiWJ+DpfyrpekuvdLDuYUjq0XFfTbsKiCI0h8A0F2Tiwtc4mTFAcPlk49PHOsKsKFUKbGFTwSG3H53/e8+aZxH05XV1Y5uKxenNPGMlHVCRkKhdCK7nuClnbBAPSv3GgjFhiYvhteO15P0XiAahjC/Gs2pG8kSO3Y=
